### ISSUE TITLE
Error when deploying the test environnment

### ISSUE THREAD

**Issue by SamirFarhat** [mspnp/ha-nva#39]
I'm trying to deploy the test environment using the provided script, just like documented.
After few minutes of deployment, i hit the following error:
########################
New-AzureRmResourceGroupDeployment : 3:15:14 PM - Resource Microsoft.Compute/virtualMachines/extensions 'ha-nva-web-vm3/apache-config-ext' failed with message '{
  "status": "Failed",
  "error": {
    "code": "ResourceDeploymentFailure",
    "message": "The resource operation completed with terminal provisioning state 'Failed'.",
    "details": [
      {
        "code": "VMExtensionProvisioningError",
        "message": "VM has reported a failure when processing extension 'apache-config-ext'. Error message: \"Malformed status file [000003] Invalid status/status: failed\"."
      }
    ]
  }
}'
At C:\Users\s.farhat\Dropbox\Blog\MVP\Azure Networking\NVA HA\NVAZookeeper\ha-nva-deployment\sample-test-environment\Deploy.ps1:51 char:1
+ New-AzureRmResourceGroupDeployment -Name "ha-web-lb-vms-deployment" - ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-AzureRmResourceGroupDeployment], Exception
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.NewAzureResourceGroupDeploymentCmdlet
#############################
The VMs has been deployed but looks like a custom extension has failed

![snag-0143](https://user-images.githubusercontent.com/14938496/27336827-018501e0-55d1-11e7-8dcc-e440be39ff01.png)
![snag-0144](https://user-images.githubusercontent.com/14938496/27336828-0187d14a-55d1-11e7-9b40-a59b0286a4a9.png)

**Comment by SamirFarhat** [comment]
Note that the Firewall VMs were not deployed

**Comment by atoakley** [comment]
Can you test this now?  We did not change the uri when we moved the template building blocks to v2.0 for the templates and it could have caused this to fail.  We have just merged PR #44 that should resolve this.
