### ISSUE TITLE
Gettting the following error whe I deploy

### ISSUE THREAD

**Issue by rdearm1** [mspnp/ha-nva#41]
I have filled in the subnet, resource group, and username/password parameters but I still get this error.

Using https://raw.githubusercontent.com/mspnp/template-building-blocks/master/ to locate templates

Deploying docker vms...
New-AzureRmResourceGroupDeployment : 11:46:55 AM - Resource Microsoft.Network/networkInterfaces
'ha-nva-docker-vm1-nic1' failed with message '{
  "error": {
    "code": "InvalidResourceReference",
    "message": "Resource /subscriptions/bf1554a4-ef1a-4cb7-b1c8-06c5165d548e/resourceGroups/ha-nva-rg/providers/Microso
ft.Network/virtualNetworks/VNET-01-TRANSIT/subnets/PRIVATE1-10.255.4.0 referenced by resource /subscriptions/bf1554a4-e
f1a-4cb7-b1c8-06c5165d548e/resourceGroups/ha-nva-rg/providers/Microsoft.Network/networkInterfaces/ha-nva-docker-vm1-nic
1 was not found. Please make sure that the referenced resource exists, and that both resources are in the same
region.",
    "details": []
  }
}'
At C:\Users\azarch\Desktop\ha-nva-master\ha-nva-deployment\Deploy.ps1:40 char:1
+ New-AzureRmResourceGroupDeployment -Name "ra-docker-deployment" -Reso ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-AzureRmResourceGroupDeployment], Exception
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.NewAzureResourceGroupDep
   loymentCmdlet

**Comment by atoakley** [comment]
This should be fixed in PR #44.  We did not change the uri when we moved the template building blocks to v2.0.
