### ISSUE TITLE
Relevant contents are removed 

### ISSUE THREAD

**Issue by hosseinmiri** [mspnp/ha-nva#43]
All relevant contents and JSON files are removed from mspnp/template-building-blocks/master/templates/buildingBlocks!! What is the point of publishing something which is linked to a nonexisting solution ???

New-AzureRmResourceGroupDeployment : 12:45:16 PM - Error: Code=InvalidContentLink; Message=Unable to download deployment content from 
'https://raw.githubusercontent.com/mspnp/template-building-blocks/master/templates/buildingBlocks/vnet-n-subnet/azuredeploy.json'. The tracking Id is '5e1bb31e-0272-4eb2-a2a1-e29ee4e0c61f'. 
Please see https://aka.ms/arm-deploy for usage details.
At
+ New-AzureRmResourceGroupDeployment -Name "ha-vnet-deployment" -Resour ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-AzureRmResourceGroupDeployment], Exception
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.NewAzureResourceGroupDeploymentCmdlet

**Comment by damray** [comment]
Same issue here and the https://raw.githubusercontent.com/mspnp/template-building-blocks/v1.0.0/templates/buildingBlocks/multi-vm-n-nic-m-storage/azuredeploy.json is not working in term of parameter also...

**Comment by atoakley** [comment]
This should be fixed in PR #44.  We did not change the uri when we moved the template building blocks to v2.0.
