### ISSUE TITLE
new Active-Active architecture using HA-Ports on ILBs

### ISSUE THREAD

**Issue by kiwibayer** [mspnp/ha-nva#52]
can we update the recommendations here with the patterns on: 
https://docs.microsoft.com/en-us/azure/load-balancer/load-balancer-ha-ports-overview#nva

**Comment by hallihan** [comment]
@kiwibayer - This would be a good candidate for a pull request if you are still working with this reference implementation.

**Comment by hallihan** [comment]
This solution is no longer being updated, see https://docs.microsoft.com/azure/architecture/reference-architectures/dmz/nva-ha for the latest options.
