### ISSUE TITLE
ould not find or load main class com.microsoft.azure.practices......

### ISSUE THREAD

**Issue by momomo1111** [mspnp/ha-nva#60]
Hi Guys

Im getting this error on when i check the logs after running the following command:
sudo docker run --name clientMonitor1........................................

_Error: Could not find or load main class com.microsoft.azure.practices.nvadaemon.Main
/nva-docker-entrypoint.sh
su-exec_

Any ideas on how to fix?

Thanks

momo

**Comment by hallihan** [comment]
This solution is no longer being updated, see https://docs.microsoft.com/azure/architecture/reference-architectures/dmz/nva-ha for the latest options.
